[package]
name = "ggengine_proc_macros"
description = "GGEngine proc-macro crate supplies derive macros that automatically implement ECS traits."

version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.*"
quote = "1.*"
