#include "MainWindowUi.h"


void ui::MainWindowUi::setupUi(QMainWindow *MainWindow) {
    if (MainWindow->objectName().isEmpty())
        MainWindow->setObjectName(QString("MainWindow"));
    MainWindow->resize(1400, 1000);
    MainWindow->move(QDesktopWidget().screenGeometry().width() / 2 - 700, 0);
    QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
    MainWindow->setSizePolicy(sizePolicy);
    MainWindow->setMinimumSize(QSize(1400, 1000));
    MainWindow->setMaximumSize(QSize(1400, 1000));
    actionNew_Project = new QAction(MainWindow);
    actionNew_Project->setObjectName(QString("actionNew_Project"));
    actionOpen_Project = new QAction(MainWindow);
    actionOpen_Project->setObjectName(QString("actionOpen_Project"));
    QIcon icon;
    icon.addFile(QString("../C++/Programs/CGG Designer/images/OpenIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
    actionOpen_Project->setIcon(icon);
    actionOpen_Recent = new QAction(MainWindow);
    actionOpen_Recent->setObjectName(QString("actionOpen_Recent"));
    actionClose_Project = new QAction(MainWindow);
    actionClose_Project->setObjectName(QString("actionClose_Project"));
    actionSettings = new QAction(MainWindow);
    actionSettings->setObjectName(QString("actionSettings"));
    QIcon icon1;
    icon1.addFile(QString("../C++/Programs/CGG Designer/images/SettingsIcon.png"), QSize(), QIcon::Normal, QIcon::Off);
    actionSettings->setIcon(icon1);
    actionExit = new QAction(MainWindow);
    actionExit->setObjectName(QString("actionExit"));
    QIcon icon2;
    icon2.addFile(QString("../C++/Programs/CGG Designer/images/ExitIcon.webp"), QSize(), QIcon::Normal, QIcon::Off);
    actionExit->setIcon(icon2);
    actionUndo = new QAction(MainWindow);
    actionUndo->setObjectName(QString("actionUndo"));
    actionUndo->setCheckable(false);
    actionRedo = new QAction(MainWindow);
    actionRedo->setObjectName(QString("actionRedo"));
    actionGet_generated_code = new QAction(MainWindow);
    actionGet_generated_code->setObjectName(QString("actionGet_generated_code"));
    actionGetGeneratedCode = new QAction(MainWindow);
    actionGetGeneratedCode->setObjectName(QString("actionGetGeneratedCode"));
    actionConvert_in_C = new QAction(MainWindow);
    actionConvert_in_C->setObjectName(QString("actionConvert_in_C"));
    centralwidget = new QWidget(MainWindow);
    centralwidget->setObjectName(QString("centralwidget"));
    tabWidget_Hierarchy = new QTabWidget(centralwidget);
    tabWidget_Hierarchy->setObjectName(QString("tabWidget_Hierarchy"));
    tabWidget_Hierarchy->setGeometry(QRect(0, 0, 271, 411));
    hierarchy = new QWidget();
    hierarchy->setObjectName(QString("hierarchy"));
    pushButton_AddScene = new QPushButton(hierarchy);
    pushButton_AddScene->setObjectName(QString("pushButton_AddScene"));
    pushButton_AddScene->setEnabled(false);
    pushButton_AddScene->setGeometry(QRect(0, 0, 71, 31));
    treeWidget_Hierarchy = new QTreeWidget(hierarchy);
    treeWidget_Hierarchy->setObjectName(QString("treeWidget_Hierarchy"));
    treeWidget_Hierarchy->setGeometry(QRect(0, 30, 261, 351));
    treeWidget_Hierarchy->setColumnCount(0);
    tabWidget_Hierarchy->addTab(hierarchy, QString());
    tabWidget_Inspector = new QTabWidget(centralwidget);
    tabWidget_Inspector->setObjectName(QString("tabWidget_Inspector"));
    tabWidget_Inspector->setGeometry(QRect(1116, 0, 281, 771));
    inspector = new QWidget();
    inspector->setObjectName(QString("inspector"));
    label_GameObjectName = new QLabel(inspector);
    label_GameObjectName->setObjectName(QString("label_GameObjectName"));
    label_GameObjectName->setGeometry(QRect(0, 0, 151, 31));
    QFont font;
    font.setPointSize(12);
    label_GameObjectName->setFont(font);
    lineEdit_GameObjectName = new QLineEdit(inspector);
    lineEdit_GameObjectName->setObjectName(QString("lineEdit_GameObjectName"));
    lineEdit_GameObjectName->setEnabled(false);
    lineEdit_GameObjectName->setGeometry(QRect(150, 0, 121, 31));
    label_GameObjectTag = new QLabel(inspector);
    label_GameObjectTag->setObjectName(QString("label_GameObjectTag"));
    label_GameObjectTag->setGeometry(QRect(0, 30, 151, 31));
    label_GameObjectTag->setFont(font);
    lineEdit_GameObjectTag = new QLineEdit(inspector);
    lineEdit_GameObjectTag->setObjectName(QString("lineEdit_GameObjectTag"));
    lineEdit_GameObjectTag->setEnabled(false);
    lineEdit_GameObjectTag->setGeometry(QRect(150, 30, 121, 31));
    groupBox_Components = new QGroupBox(inspector);
    groupBox_Components->setObjectName(QString("groupBox_Components"));
    groupBox_Components->setGeometry(QRect(0, 80, 271, 661));
    groupBox_Components->setFont(font);
    pushButton_AddComponent = new QPushButton(groupBox_Components);
    pushButton_AddComponent->setObjectName(QString("pushButton_AddComponent"));
    pushButton_AddComponent->setEnabled(false);
    pushButton_AddComponent->setGeometry(QRect(0, 20, 91, 23));
    QFont font1;
    font1.setPointSize(8);
    pushButton_AddComponent->setFont(font1);
    treeWidget_Components = new QTreeWidget(groupBox_Components);
    treeWidget_Components->setObjectName(QString("treeWidget_Components"));
    treeWidget_Components->setGeometry(QRect(0, 40, 271, 621));
    treeWidget_Components->setColumnCount(0);
    tabWidget_Inspector->addTab(inspector, QString());
    frame_Preview = new QFrame(centralwidget);
    frame_Preview->setObjectName(QString("frame_Preview"));
    frame_Preview->setGeometry(QRect(280, 30, 821, 741));
    frame_Preview->setFrameShape(QFrame::Box);
    frame_Preview->setFrameShadow(QFrame::Raised);
    frame_Preview->setLineWidth(2);
    groupBox = new QGroupBox(centralwidget);
    groupBox->setObjectName(QString("groupBox"));
    groupBox->setGeometry(QRect(0, 420, 271, 351));
    label_CreateGameObjectTag = new QLabel(groupBox);
    label_CreateGameObjectTag->setObjectName(QString("label_CreateGameObjectTag"));
    label_CreateGameObjectTag->setGeometry(QRect(10, 50, 151, 31));
    label_CreateGameObjectTag->setFont(font);
    label_CreateGameObjectName = new QLabel(groupBox);
    label_CreateGameObjectName->setObjectName(QString("label_CreateGameObjectName"));
    label_CreateGameObjectName->setGeometry(QRect(10, 20, 151, 31));
    label_CreateGameObjectName->setFont(font);
    lineEdit_CreateGameObjectName = new QLineEdit(groupBox);
    lineEdit_CreateGameObjectName->setObjectName(QString("lineEdit_CreateGameObjectName"));
    lineEdit_CreateGameObjectName->setEnabled(false);
    lineEdit_CreateGameObjectName->setGeometry(QRect(160, 20, 101, 31));
    lineEdit_CreateGameObjectTag = new QLineEdit(groupBox);
    lineEdit_CreateGameObjectTag->setObjectName(QString("lineEdit_CreateGameObjectTag"));
    lineEdit_CreateGameObjectTag->setEnabled(false);
    lineEdit_CreateGameObjectTag->setGeometry(QRect(160, 50, 101, 31));
    checkBox_Hitbox = new QCheckBox(groupBox);
    checkBox_Hitbox->setObjectName(QString("checkBox_Hitbox"));
    checkBox_Hitbox->setEnabled(false);
    checkBox_Hitbox->setGeometry(QRect(10, 90, 101, 17));
    checkBox_Hitbox->setFont(font);
    spinBox_X = new QSpinBox(groupBox);
    spinBox_X->setObjectName(QString("spinBox_X"));
    spinBox_X->setEnabled(false);
    spinBox_X->setGeometry(QRect(40, 110, 42, 22));
    label_X = new QLabel(groupBox);
    label_X->setObjectName(QString("label_X"));
    label_X->setEnabled(false);
    label_X->setGeometry(QRect(20, 110, 21, 21));
    QFont font2;
    font2.setBold(true);
    font2.setWeight(75);
    label_X->setFont(font2);
    label_X->setAlignment(Qt::AlignCenter);
    label_Y = new QLabel(groupBox);
    label_Y->setObjectName(QString("label_Y"));
    label_Y->setEnabled(false);
    label_Y->setGeometry(QRect(100, 110, 21, 21));
    label_Y->setFont(font2);
    label_Y->setAlignment(Qt::AlignCenter);
    spinBox_Y = new QSpinBox(groupBox);
    spinBox_Y->setObjectName(QString("spinBox_Y"));
    spinBox_Y->setEnabled(false);
    spinBox_Y->setGeometry(QRect(120, 110, 42, 22));
    label_W = new QLabel(groupBox);
    label_W->setObjectName(QString("label_W"));
    label_W->setEnabled(false);
    label_W->setGeometry(QRect(20, 140, 21, 21));
    label_W->setFont(font2);
    label_W->setAlignment(Qt::AlignCenter);
    spinBox_W = new QSpinBox(groupBox);
    spinBox_W->setObjectName(QString("spinBox_W"));
    spinBox_W->setEnabled(false);
    spinBox_W->setGeometry(QRect(40, 140, 42, 22));
    spinBox_H = new QSpinBox(groupBox);
    spinBox_H->setObjectName(QString("spinBox_H"));
    spinBox_H->setEnabled(false);
    spinBox_H->setGeometry(QRect(120, 140, 42, 22));
    label_H = new QLabel(groupBox);
    label_H->setObjectName(QString("label_H"));
    label_H->setEnabled(false);
    label_H->setGeometry(QRect(100, 140, 21, 21));
    label_H->setFont(font2);
    label_H->setAlignment(Qt::AlignCenter);
    checkBox_Sprite = new QCheckBox(groupBox);
    checkBox_Sprite->setObjectName(QString("checkBox_Sprite"));
    checkBox_Sprite->setEnabled(false);
    checkBox_Sprite->setGeometry(QRect(10, 180, 101, 17));
    checkBox_Sprite->setFont(font);
    label_TextureName = new QLabel(groupBox);
    label_TextureName->setObjectName(QString("label_TextureName"));
    label_TextureName->setEnabled(false);
    label_TextureName->setGeometry(QRect(30, 210, 101, 21));
    label_TextureName->setFont(font2);
    lineEdit_TextureName = new QLineEdit(groupBox);
    lineEdit_TextureName->setObjectName(QString("lineEdit_TextureName"));
    lineEdit_TextureName->setEnabled(false);
    lineEdit_TextureName->setGeometry(QRect(130, 210, 131, 21));
    plainTextEdit = new QPlainTextEdit(groupBox);
    plainTextEdit->setObjectName(QString("plainTextEdit"));
    plainTextEdit->setEnabled(false);
    plainTextEdit->setGeometry(QRect(20, 240, 241, 51));
    plainTextEdit->setFrameShape(QFrame::NoFrame);
    plainTextEdit->setLineWidth(1);
    plainTextEdit->setTabChangesFocus(false);
    plainTextEdit->setReadOnly(true);
    pushButton_CreateGameObject = new QPushButton(groupBox);
    pushButton_CreateGameObject->setObjectName(QString("pushButton_CreateGameObject"));
    pushButton_CreateGameObject->setEnabled(false);
    pushButton_CreateGameObject->setGeometry(QRect(160, 310, 101, 31));
    lineEdit_ = new QLineEdit(groupBox);
    lineEdit_->setObjectName(QString("lineEdit_"));
    lineEdit_->setEnabled(false);
    lineEdit_->setGeometry(QRect(12, 310, 131, 31));
    lineEdit_->setReadOnly(true);
    tabWidget_Terminal = new QTabWidget(centralwidget);
    tabWidget_Terminal->setObjectName(QString("tabWidget_Terminal"));
    tabWidget_Terminal->setGeometry(QRect(0, 780, 1391, 181));
    tab = new QWidget();
    tab->setObjectName(QString("tab"));
    plainTextEdit_Terminal = new QPlainTextEdit(tab);
    plainTextEdit_Terminal->setObjectName(QString("plainTextEdit_Terminal"));
    plainTextEdit_Terminal->setGeometry(QRect(10, 10, 1371, 111));
    plainTextEdit_Terminal->setReadOnly(true);
    lineEdit_Terminal = new QLineEdit(tab);
    lineEdit_Terminal->setObjectName(QString("lineEdit_Terminal"));
    lineEdit_Terminal->setEnabled(false);
    lineEdit_Terminal->setGeometry(QRect(40, 130, 1341, 20));
    pushButton_Terminal = new QPushButton(tab);
    pushButton_Terminal->setObjectName(QString("pushButton_Terminal"));
    pushButton_Terminal->setEnabled(false);
    pushButton_Terminal->setGeometry(QRect(0, 130, 41, 21));
    tabWidget_Terminal->addTab(tab, QString());
    pushButton_Play = new QPushButton(centralwidget);
    pushButton_Play->setObjectName(QString("pushButton_Play"));
    pushButton_Play->setEnabled(false);
    pushButton_Play->setGeometry(QRect(640, 0, 41, 23));
    pushButton_Play->setFont(font2);
    pushButton_Pause = new QPushButton(centralwidget);
    pushButton_Pause->setObjectName(QString("pushButton_Pause"));
    pushButton_Pause->setEnabled(false);
    pushButton_Pause->setGeometry(QRect(700, 0, 41, 23));
    pushButton_Pause->setFont(font2);
    MainWindow->setCentralWidget(centralwidget);
    menubar = new QMenuBar(MainWindow);
    menubar->setObjectName(QString("menubar"));
    menubar->setGeometry(QRect(0, 0, 1400, 21));
    menuProject = new QMenu(menubar);
    menuProject->setObjectName(QString("menuProject"));
    menuEdit = new QMenu(menubar);
    menuEdit->setObjectName(QString("menuEdit"));
    menuCode = new QMenu(menubar);
    menuCode->setObjectName(QString("menuCode"));
    MainWindow->setMenuBar(menubar);
    statusbar = new QStatusBar(MainWindow);
    statusbar->setObjectName(QString("statusbar"));
    MainWindow->setStatusBar(statusbar);

    menubar->addAction(menuProject->menuAction());
    menubar->addAction(menuEdit->menuAction());
    menubar->addAction(menuCode->menuAction());
    menuProject->addAction(actionNew_Project);
    menuProject->addAction(actionOpen_Project);
    menuProject->addAction(actionOpen_Recent);
    menuProject->addAction(actionClose_Project);
    menuProject->addSeparator();
    menuProject->addAction(actionSettings);
    menuProject->addSeparator();
    menuProject->addAction(actionExit);
    menuEdit->addAction(actionUndo);
    menuEdit->addAction(actionRedo);
    menuCode->addAction(actionGetGeneratedCode);
    menuCode->addSeparator();
    menuCode->addAction(actionConvert_in_C);

    retranslateUi(MainWindow);

    tabWidget_Hierarchy->setCurrentIndex(0);
    tabWidget_Inspector->setCurrentIndex(0);
    tabWidget_Terminal->setCurrentIndex(0);


    QMetaObject::connectSlotsByName(MainWindow);
}

void ui::MainWindowUi::retranslateUi(QWidget *MainWindow) {
    MainWindow->setWindowTitle(QApplication::translate("MainWindow", "GG Designer", Q_NULLPTR));
    actionNew_Project->setText(QApplication::translate("MainWindow", "New Project", Q_NULLPTR));
    actionOpen_Project->setText(QApplication::translate("MainWindow", "Open Project", Q_NULLPTR));
    actionOpen_Recent->setText(QApplication::translate("MainWindow", "Open Recent", Q_NULLPTR));
    actionClose_Project->setText(QApplication::translate("MainWindow", "Close Project", Q_NULLPTR));
    actionSettings->setText(QApplication::translate("MainWindow", "Settings", Q_NULLPTR));
    actionExit->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
    actionUndo->setText(QApplication::translate("MainWindow", "Undo", Q_NULLPTR));
    actionRedo->setText(QApplication::translate("MainWindow", "Redo", Q_NULLPTR));
    actionGet_generated_code->setText(QApplication::translate("MainWindow", "Get generated code", Q_NULLPTR));
    actionGetGeneratedCode->setText(QApplication::translate("MainWindow", "Get generated code", Q_NULLPTR));
    actionConvert_in_C->setText(QApplication::translate("MainWindow", "Convert in C++", Q_NULLPTR));
    pushButton_AddScene->setText(QApplication::translate("MainWindow", "Add Scene", Q_NULLPTR));
    tabWidget_Hierarchy->setTabText(tabWidget_Hierarchy->indexOf(hierarchy),
                                    QApplication::translate("MainWindow", "Hierarchy", Q_NULLPTR));
    label_GameObjectName->setText(QApplication::translate("MainWindow", "gameobject_name -", Q_NULLPTR));
    label_GameObjectTag->setText(QApplication::translate("MainWindow", "gameobject_tag    -", Q_NULLPTR));
    groupBox_Components->setTitle(QApplication::translate("MainWindow", "Components", Q_NULLPTR));
    pushButton_AddComponent->setText(QApplication::translate("MainWindow", "Add component", Q_NULLPTR));
    tabWidget_Inspector->setTabText(tabWidget_Inspector->indexOf(inspector),
                                    QApplication::translate("MainWindow", "GameObject Inspector", Q_NULLPTR));
    groupBox->setTitle(QApplication::translate("MainWindow", "Create GameObject", Q_NULLPTR));
    label_CreateGameObjectTag->setText(QApplication::translate("MainWindow", "gameobject_tag    -", Q_NULLPTR));
    label_CreateGameObjectName->setText(QApplication::translate("MainWindow", "gameobject_name -", Q_NULLPTR));
    checkBox_Hitbox->setText(QApplication::translate("MainWindow", "with Hitbox", Q_NULLPTR));
    label_X->setText(QApplication::translate("MainWindow", "X", Q_NULLPTR));
    label_Y->setText(QApplication::translate("MainWindow", "Y", Q_NULLPTR));
    label_W->setText(QApplication::translate("MainWindow", "W", Q_NULLPTR));
    label_H->setText(QApplication::translate("MainWindow", "H", Q_NULLPTR));
    checkBox_Sprite->setText(QApplication::translate("MainWindow", "with Sprite", Q_NULLPTR));
    label_TextureName->setText(QApplication::translate("MainWindow", "Texture name -", Q_NULLPTR));
    plainTextEdit->setPlainText(QApplication::translate("MainWindow",
                                                        "You will need to implement the Texture class yourself, and name the pointer to instance of type Texture* as \"Texture name\"",
                                                        Q_NULLPTR));
    pushButton_CreateGameObject->setText(QApplication::translate("MainWindow", "Create", Q_NULLPTR));
    lineEdit_->setText(QString());
    lineEdit_->setPlaceholderText(QApplication::translate("MainWindow", "Error message", Q_NULLPTR));
    lineEdit_Terminal->setInputMask(QString());
    lineEdit_Terminal->setText(QString());
    pushButton_Terminal->setText(QApplication::translate("MainWindow", ">>>", Q_NULLPTR));
    tabWidget_Terminal->setTabText(tabWidget_Terminal->indexOf(tab),
                                   QApplication::translate("MainWindow", "GGameEngine terminal", Q_NULLPTR));
    pushButton_Play->setText(QApplication::translate("MainWindow", "|>", Q_NULLPTR));
    pushButton_Pause->setText(QApplication::translate("MainWindow", "| |", Q_NULLPTR));
    menuProject->setTitle(QApplication::translate("MainWindow", "Project", Q_NULLPTR));
    menuEdit->setTitle(QApplication::translate("MainWindow", "&Edit", Q_NULLPTR));
    menuCode->setTitle(QApplication::translate("MainWindow", "Code", Q_NULLPTR));
}
